version: 0.1

runtimes:
  enabled:
    - node@18.12.1
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [ALL]
      commands:
        - output: parsable
          run: ${plugin}/todo-finder.sh
          success_codes: [0, 1]