---
version: 0.1
cli:
  version: 1.22.2

runtimes:
  definitions:
    - type: python
      linter_environment:
        - name: PYTHONPATH
          list:
            - "/home/alwi/Entwicklung/KNIIT/kniit_hub/env_kniit_dev/bin/python3.10"
        - name: VIRTUAL_ENV
          list:
            - "/home/alwi/Entwicklung/KNIIT/kniit_hub/env_kniit_dev/bin"
      runtime_environment:
        - name: HOME
          value: ${home}
        - name: PATH
          list:
            - ${runtime}/bin
  enabled:
    - go@1.21.0
    - node@22.4.0
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [shell]
      commands:
        - output: rewrite
          run: ${plugin}/todo-finder-parser.sh
          success_codes: [0, 1]
    - name: prettier
      files:
        - typescript
        - yaml
        - css
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
      extra_packages: [prettier-plugin-svelte]

  enabled:
    - prettier@3.3.3
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.8.0
    - checkov@3.2.225
    - eslint@9.9.0
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - pylint@3.2.6
    - ruff@0.5.7
    - trivy@0.54.1
    - trufflehog@3.81.8
    - yamllint@1.35.1
