version: 0.1

runtimes:
  enabled:
    - go@1.21.0
    - node@18.12.1
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [ALL]
      commands:
        - output: rewrite
          run: ${plugin}/todo-finder-parser.sh
          success_codes: [0, 1]
    - name: prettier-plugin-svelte
      files: [ALL]
      # npm install prettier-plugin-svelte
      runtime: node
      package: prettier-plugin-svelte
  enabled:
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.4.2
    - checkov@3.2.176
    - eslint@9.6.0
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - prettier@3.3.2
    - pylint@3.2.5
    - ruff@0.5.1
    - trivy@0.52.2
    - trufflehog@3.79.0
    - yamllint@1.35.1
