version: 0.1

runtimes:
  enabled:
    - node@18.12.1
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [ALL]
      commands:
        - output: parsable
          run: ${plugin}/todo-finder.sh
          success_codes: [0, 1]
  enabled:
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.4.2
    - checkov@3.2.164
    - eslint@9.6.0
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - prettier@3.3.2
    - pylint@3.2.5
    - ruff@0.5.0
    - trivy@0.52.2
    - trufflehog@3.79.0
    - yamllint@1.35.1