---
version: 0.1
cli:
  version: 1.22.2

runtimes:
  enabled:
    - go@1.21.0
    - node@22.4.0
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [shell]
      commands:
        - output: rewrite
          run: ${plugin}/todo-finder-parser.sh
          success_codes: [0, 1]
    - name: prettier
      files:
        - typescript
        - yaml
        - css
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
      extra_packages: [prettier-plugin-svelte]
    - name: pylint
      runtime: python
      commands:
        - name: lint
          # Custom parser type defined in the trunk cli to handle pylint's JSON output.
          output: pylint
          run: pylint --exit-zero --output ${tmpfile} --output-format json ${target}
          success_codes: [0]
          read_output_from: tmp_file
          batch: true
          cache_results: true
      tools: [pylint]
      suggest_if: config_present
      direct_configs:
        - pylintrc
        - .pylintrc
      affects_cache:
        - pyproject.toml
        - setup.cfg
      issue_url_format: http://pylint-messages.wikidot.com/messages:{}
      known_good_version: 2.11.1
      version_command:
        parse_regex: pylint ${semver}
        run: pylint --version

  enabled:
    - prettier@3.3.3
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.8.0
    - checkov@3.2.225
    - eslint@9.9.0
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - pylint@3.2.6
    - ruff@0.5.7
    - trivy@0.54.1
    - trufflehog@3.81.8
    - yamllint@1.35.1
