---
version: 0.1
cli:
  version: 1.22.5

runtimes:
  enabled:
    - go@1.21.0
    - node@22.6.0
    - python@3.10.8

lint:
  threshold:
    - linters: [todo-finder]
      level: None
  definitions:
    - name: todo-finder
      files:
        - python
        - typescript
      commands:
        - output: regex
          run: grep --with-filename --line-number --ignore-case todo ${target}
          success_codes: [0, 1]
          parse_regex: "((?P<path>.*):(?P<line>\\d+):(?P<col>\\d+):
            \\[(?P<severity>.*)\\] (?P<message>.*) \\((?P<code>.*)\\))"
          read_output_from: stdout
          parser:
            run: "sed -E 's/(.*):([0-9]+):(.*)/\\1:\\2:0:
              [error] Found todo in \"\\3\" (found-todo)/'"
    - name: prettier
      files:
        - typescript
        - yaml
        - css
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
      extra_packages: [prettier-plugin-svelte]
  enabled:
    - prettier@3.3.3
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.8.0
    - checkov@3.2.255
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - ruff@0.6.7
    - taplo@0.9.3
    - trivy@0.55.2:
        commands: [config, fs-vuln, fs-secret]
    - trufflehog@3.82.2
    - yamllint@1.35.1
    - todo-finder

actions:
  enabled:
    - trunk-announce
    - trunk-check-pre-push
    - trunk-fmt-pre-commit
    - trunk-upgrade-available
