---
version: 0.1
cli:
  version: 1.22.2

runtimes:
  enabled:
    - go@1.21.0
    - node@22.4.0
    - python@3.10.8

lint:
  definitions:
    - name: todo-finder
      files: [shell]
      commands:
        - output: rewrite
          run: ${plugin}/todo-finder-parser.sh
          success_codes: [0, 1]
    - name: prettier
      files:
        - typescript
        - yaml
        - css
        - postcss
        - sass
        - html
        - markdown
        - json
        - javascript
        - graphql
        - prettier_supported_configs
      extra_packages: [prettier-plugin-svelte]

  enabled:
    - prettier@3.3.2
    - shellcheck@0.10.0
    - shfmt@3.6.0
    - actionlint@1.7.1
    - bandit@1.7.9
    - black@24.4.2
    - checkov@3.2.176
    - eslint@8.56.0
    - git-diff-check
    - isort@5.13.2
    - markdownlint@0.41.0
    - pylint@3.2.5
    - ruff@0.5.1
    - trivy@0.52.2
    - trufflehog@3.79.0
    - yamllint@1.35.1
